import { useTranslation } from "react-i18next";

import { LegalDocument } from "../LegalDocument";
import { LegalLayout } from "../LegalLayout";

function EnglishLegalContent() {
  const { t } = useTranslation();

  return (
    <>
      <h1>{t("legal.pages.acceptableUsePolicy.blocks.acceptableUsePolicyAupMundpay")}</h1>
      <p>
        {t("legal.pages.acceptableUsePolicy.blocks.lastUpdatedApril12026")}
        <br />
        <br />
        {t("legal.pages.acceptableUsePolicy.blocks.contactForQuestionsReportsDenunciasMundpayComSubject")}
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.thisAcceptableUsePolicyAupDefinesProhibitedOr")}</p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.byUsingTheMundpayPlatformYouAgreeTo")}</p>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.generalGuidelinesAndEnforcement")}</h3>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.mundpayMayMonitorAuditAndInvestigateActivitiesAnd")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.mundpayMayAtAnyTimeRemoveMaterialsSuspend")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.theInterpretationAndDecisionOnViolationsAreOf")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.reportsOrQuestionsDenunciasMundpayCom")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.productRegistrationAndListingPhysicalAndDigital")}</h3>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.theSellerMayRegisterPhysicalAndDigitalProducts")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.approvalMayOccurAutomaticallyAndPostMonitoredMundpay")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.theSellerIsEntirelyResponsibleForTheContent")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.restrictedActivitiesAndProhibitedProducts")}</h3>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.itIsExpresslyProhibitedWithinTheMundpayPlatform")}</p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.theProhibitionAlsoAppliesToActivitiesThatMay")}</p>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.illegalProductsServicesAndFraudulentActivities")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.theseIncludeButAreNotLimitedTo")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.commercializationOfAnyProductOrServiceThatIs")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.documentForgeryServicesIncludingIdentityDocumentsDiplomasOr")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.provisionOfFalseIdentitiesSimulatedRegistrationsOrFalse")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.activitiesInvolvingHumanTraffickingHumanExploitationContractKilling")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.commercializationOfHumanBodyPartsBiologicalMaterialsFluids")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.contentOrServicesThatEncouragePromoteOrCelebrate")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.espionageHackingAndPrivacyViolations")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.theCommercializationOrPromotionOfTheFollowingIs")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.espionageApplicationsClandestineMonitoringOrUnauthorizedTracking")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.hackingToolsOrUnauthorizedAccessToThirdParty")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.softwareDesignedToCaptureDataCredentialsOrCommunications")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.drugsNarcoticsAndControlledSubstances")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.thisCovers")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.illicitSubstancesNarcoticsOrRecreationalDrugs")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.productsIntendedForTheProductionPreparationOrConsumption")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.hydroponicEquipmentOrCultivationSetupsAimedAtProducing")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.cannabisDerivativesIncludingCbdInNonComplianceWith")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.coursesContentOrMaterialsThatTeachTheCultivation")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.weaponsExplosivesAndHazardousMaterials")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.theseInclude")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.firearmsAmmunitionGunpowderExplosivesAndFireworks")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.componentsAccessoriesConversionKitsOrWeaponParts")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.item042")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.tacticalKnivesMachetesQuickOpeningBladesAndDisguised")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.flammableRadioactiveToxicOrHazardousChemicalMaterials")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.pepperSpraysTasersAndElectroshockDevices")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.adultContentAndServices")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.theCommercializationOrIntermediationOfTheFollowingIs")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.pornographyExplicitNudityOrSexualContent")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.prostitutionServicesEscortsOrFetishServices")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.datingPlatformsMatchmakingServicesOrSimilar")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.adultEntertainmentClubsStripTeaseVenuesOrRelated")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.gamblingAndBetting")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.theseInclude2")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.casinosSportsBettingLotteriesAndRaffles")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.bettingCoursesPaidSignalsOrPrognosisServices")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.tournamentsWithCashPrizes")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.auctionsWithPerBidFees")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.anyFormOfGameInvolvingRandomFinancialGains")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.financialServicesCreditAndInvestments")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.theUseOfMundpayForTheFollowingIs")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.loansFinancingOrDirectCredit")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.buyNowPayLaterBnpl")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.debtNegotiationSettlementOrConsolidation")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.creditScoreRepairOrCreditCounseling")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.insuranceHealthBenefitsOrInsuranceRelatedProducts")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.moneyTransmissionRemittancesOrForeignExchange")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.neobanksDigitalAccountsCustodyOrFunding")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.saleOfSharesSecuritiesOrCollectiveInvestments")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.investmentSchemesWithPromisedReturns")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.cryptoAssetsTokensAndStoredValue")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.thisCovers2")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.cryptocurrencyExchangesWalletsOrCustodyServices")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.icosStakingAndMining")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.primaryOrSecondaryNfts")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.saleOfInGameVirtualCurrencies")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.giftCardsPrepaidCardsOrStoredDigitalCredits")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.simCardsPhoneCardsAndDigitalCredits")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.intellectualPropertyAndCounterfeiting")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.theCommercializationOfTheFollowingIsProhibited")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.counterfeitProductsOrReplicas")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.licensedProductsSoldWithoutAuthorization")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.digitalPiracySoftwareFilmsMusic")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.platformOrSocialMediaAccounts")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.followerServicesArtificialEngagementOrFraudulentPaidTraffic")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.websitesOrServicesThatFacilitateCopyrightInfringement")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.abusiveMarketingAndDeceptivePractices")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.theseInclude3")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.pyramidSchemesOrIrregularMultiLevelMarketing")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.getRichQuickPromises")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.investmentRobotsOrFinancialAutomationSchemes")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.falseTestimonialsOrUnsubstantiatedClaims")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.aggressiveOrPredatorySalesPractices")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.offersWithUnrealisticGains")}</p>
        </li>
      </ul>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.anyFalseOrMisleadingClaimIsExpresslyProhibited")}</p>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.irregularIntermediationAndPaymentAggregation")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.theFollowingIsProhibited")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.receivingFundsForProductsOfUnregisteredThirdParties")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.actingAsASubAcquirerFacilitatorOrAggregator")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.operatingCrowdfundingDonationsOrFundraisingCampaigns")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.settlingSalesWithoutDeliveryOfAProductOr")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.publicAndGovernmentServices")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.restrictionsInclude")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.offeringGovernmentBenefits")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.servicesOnBehalfOfConsulatesOrEmbassies")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.intermediationOfPublicServicesWithoutAuthorization")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.irregularTelecommunicationsAndTechnology")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.thisCovers3")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.iptvTvBoxOrIllegalStreamingServices")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.signalJammers")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.clandestineDecoders")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.nonCertifiedTelecommunicationsEquipment")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.recalledUnsafeOrRegulatedProducts")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.theCommercializationOfTheFollowingIsProhibited2")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.productsUnderActiveRecall")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.itemsDeemedUnsafeByRegulatoryAuthorities")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.nonCertifiedMedicalEquipment")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.machineryWithoutSafetyDevices")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.productsRequiringGovernmentCertification")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.otherRestrictedCategories")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.alsoIncludedAmongOthers")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.tobaccoElectronicCigarettesAndRelatedProducts")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.alcoholicBeveragesAndAgeRestrictedProducts")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.animalsFloraAndDerivatives")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.irregularVehicles")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.eventTickets")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.foodAndBeveragesWithoutALicense")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.controlledPesticides")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.emailListsAndPersonalDatabasesInComplianceWith")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.highRiskPhysicalProducts")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.dueToInternalRiskLogisticsFraudAndChargeback")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.electronicsCellPhonesNotebooksSmartwatchesConsoles")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.giftCardsAndDigitalCredits")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.perfumesAndCosmetics")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.homeAppliances")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.digitalAccountsOrVirtualAssets")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.productsWidelyTargetedByLogisticalFraudOrChargebacks")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.restrictedItemsAndActivitiesSubjectToPreApproval")}</h3>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.theFollowingRequireRiskAnalysisAndExpressAuthorization")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.supplementsNutraceuticalsAndHealthClaimsWeightLossLibido")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.cryptoDigitalAssetsCustodyOnOffRampNfts")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.ticketsEventsDonationsCrowdfundingWithinPermittedLimitsSubscription")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.regulatedProductsWithCertificationsAnvisaAnatelInmetroFda")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.nonExplicitAdultContentWithModerationAgeGating")}</p>
        </li>
      </ul>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.approvalMayBeDeniedOrRevokedAtAny")}</p>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.minimumCommercialTransparencyRequirements")}</h3>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.pricingAndRecurrenceDisplayFrequencyAmountAndRenewal")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.expressConsentBeforeTheFirstChargeAndEach")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.simpleCancellationAndVisibleRefundPolicyEG")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.noDarkPatternsFalseUrgencyOrMaterialOmissions")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.healthPerformanceClaimsMustBeTruthfulVerifiableAnd")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.prohibitedUsesOfMundpayProductsInfrastructure")}</h3>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.falseIncompleteRegistrationDataFailureToReportRelevant")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.processingOnBehalfOfAnotherUnidentifiedMerchantAggregating")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.usingMundpayAsAVirtualTerminalCardTester")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.useOfMundpaySBrandLogosWithoutWritten")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.enforcementMeasuresAndConsequences")}</h3>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.uponIdentificationOfAViolationOrMaterialRisk")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.removeContentItemsBlockListingsIntegrations")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.suspendCloseAccountsAndAccess")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.retainFundsApplyRiskReservesLimitWithdrawalsAnd")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.requireDocumentsAndCorrectionsLandingPageClaimsDisclosures")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.notifyAffectedBrandsSuppliersPaymentPartnersAndWhere")}</p>
        </li>
      </ul>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.financialMeasuresRetentionsBlocksReservesFollowTheSeller")}</p>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.complaintAndContactChannel")}</h3>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.suspectedMisuseSendToDenunciasMundpayComSubject")}</p>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.amendmentsAndPrecedence")}</h3>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.weMayUpdateThisAupAtAnyTime")}</p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.inTheEventOfAConflictBetweenThis")}</p>
    </>
  );
}

function PortugueseLegalContent() {
  const { t } = useTranslation();

  return (
    <>
      <h1>{t("legal.pages.acceptableUsePolicy.blocks.politicaDeUsoAceitavelPuaMundpay")}</h1>
      <p>
        {t("legal.pages.acceptableUsePolicy.blocks.ultimaAtualizacao1DeAbrilDe2026")}
        <br />
        <br />
        {t("legal.pages.acceptableUsePolicy.blocks.contatoParaDuvidasDenunciasDenunciasMundpayComAssunto")}
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.estaPoliticaDeUsoAceitavelPuaDefineAtividades")}</p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.aoUtilizarAPlataformaMundpayVoceConcordaEm")}</p>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.diretrizesGeraisEFiscalizacao")}</h3>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.aMundpayPodeMonitorarAuditarEInvestigarAtividades")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.aMundpayPodeAQualquerMomentoRemoverMateriais")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.aInterpretacaoEADecisaoSobreViolacaoSao")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.denunciasOuDuvidasDenunciasMundpayCom")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.cadastroEListagemDeProdutosFisicosEDigitais")}</h3>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.oSellerPodeCadastrarProdutosFisicosEDigitais")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.aAprovacaoPodeOcorrerDeFormaAutomaticaE")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.oSellerEInteiramenteResponsavelPorConteudoQualidade")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.atividadesRestritasEProdutosProibidos")}</h3>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.eExpressamenteVedadaNoAmbitoDaPlataformaDa")}</p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.aVedacaoAplicaSeAindaAAtividadesQue")}</p>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.produtosServicosEAtividadesIlicitasOuDeNatureza")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.incluemSeMasNaoSeLimitamA")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.comercializacaoDeQualquerProdutoOuServicoIlegalOu")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.servicosDeFalsificacaoDeDocumentosIdentidadesDiplomasOu")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.fornecimentoDeIdentidadesFalsasCadastrosSimuladosOuReferencias")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.atividadesQueEnvolvamTraficoDePessoasExploracaoHumana")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.comercializacaoDePartesDoCorpoHumanoMateriaisBiologicos")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.conteudosOuServicosQueIncentivemPromovamOuCelebrem")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.espionagemInvasaoEViolacaoDePrivacidade")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.eVedadaAComercializacaoOuPromocaoDe")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.aplicativosDeEspionagemMonitoramentoClandestinoOuRastreamentoNao")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.ferramentasDeInvasaoHackingOuAcessoIndevidoA")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.softwaresDestinadosACapturaDeDadosCredenciaisOu")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.drogasNarcoticosESubstanciasControladas")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.abrange")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.substanciasIlicitasEntorpecentesOuDrogasRecreativas")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.produtosDestinadosAProducaoPreparoOuConsumoDe")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.equipamentosHidroponicosOuDeCultivoVoltadosAProducao")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.derivadosDeCannabisInclusiveCbdEmDesconformidadeCom")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.cursosConteudosOuMateriaisQueEnsinemCultivoProducao")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.armasExplosivosEMateriaisPerigosos")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.incluemSe")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.armasDeFogoMunicoesPolvoraExplosivosEFogos")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.componentesAcessoriosKitsDeConversaoOuPecasDe")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.armasImpressasEm3d")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.facasTaticasFacoesLaminasDeAberturaRapidaE")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.materiaisInflamaveisRadioativosToxicosOuQuimicosPerigosos")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.spraysDePimentaTasersEDispositivosDeChoque")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.conteudoEServicosAdultos")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.eProibidaAComercializacaoOuIntermediacaoDe")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.pornografiaNudezExplicitaOuConteudoSexual")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.servicosDeProstituicaoAcompanhantesOuFetiches")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.plataformasDeEncontrosServicosCasamenteirosOuSimilares")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.clubesDeEntretenimentoAdultoStripTeaseOuCorrelatos")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.jogosDeAzarEApostas")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.incluemSe2")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.cassinosApostasEsportivasLoteriasERifas")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.cursosDeApostasBettingSinaisOuPrognosticosPagos")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.torneiosComPremiacaoEmDinheiro")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.leiloesComTaxaPorLance")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.qualquerModalidadeDeJogoComGanhoFinanceiroAleatorio")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.servicosFinanceirosCreditoEInvestimentos")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.eVedadaAUtilizacaoDaMundpayPara")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.emprestimosFinanciamentosOuCreditoDireto")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.compreAgoraEPagueDepoisBnpl")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.negociacaoLiquidacaoOuConsolidacaoDeDividas")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.limpezaDeNomeOuAconselhamentoDeCredito")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.segurosBeneficiosDeSaudeOuProdutosSecuritarios")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.transmissaoDeDinheiroRemessasOuCambio")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.neobancosContasDigitaisCustodiaOuFunding")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.vendaDeAcoesValoresMobiliariosOuInvestimentosColetivos")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.esquemasDeInvestimentoComPromessaDeRetorno")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.criptoativosTokensEValoresArmazenados")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.abrange2")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.exchangesCarteirasOuCustodiaDeCriptomoedas")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.icosStakingMineracao")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.nftsPrimariosOuSecundarios")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.vendaDeMoedasVirtuaisDeJogos")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.giftCardsCartoesPrePagosOuCreditosArmazenados")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.simCardsCartoesTelefonicosECreditosDigitais")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.propriedadeIntelectualEFalsificacao")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.eProibidaAComercializacaoDe")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.produtosFalsificadosOuReplicas")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.produtosLicenciadosSemAutorizacao")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.piratariaDigitalSoftwaresFilmesMusicas")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.contasDePlataformasOuRedesSociais")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.servicosDeSeguidoresEngajamentoArtificialOuTrafegoPago")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.sitesOuServicosQueFacilitemInfracaoDeDireitos")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.marketingAbusivoEPraticasEnganosas")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.incluemSe3")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.esquemasDePiramideOuMarketingMultinivelIrregular")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.promessasDeEnriquecimentoRapido")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.robosDeInvestimentoOuAutomacoesFinanceiras")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.depoimentosFalsosOuAlegacoesNaoComprovadas")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.vendasAgressivasOuPredatorias")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.ofertasComGanhosIrreais")}</p>
        </li>
      </ul>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.eExpressamenteProibidaQualquerAlegacaoFalsaOuEnganosa")}</p>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.intermediacaoIrregularEAgregacaoDePagamentos")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.eVedado")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.receberValoresPorProdutosDeTerceirosNaoCadastrados")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.atuarComoSubadquirenteFacilitadorOuAgregadorSemAutorizacao")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.operarCrowdfundingDoacoesOuArrecadacoes")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.liquidarVendasSemEntregaDeProdutoOuServico")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.servicosPublicosEGovernamentais")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.incluemSeRestricoesA")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.ofertaDeBeneficiosGovernamentais")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.servicosEmNomeDeConsuladosOuEmbaixadas")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.intermediacaoDeServicosPublicosSemAutorizacao")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.telecomunicacoesETecnologiaIrregular")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.abrange3")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.iptvTvBoxOuStreamingIlegal")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.bloqueadoresDeSinal")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.decodificadoresClandestinos")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.telecomunicacoesNaoHomologadas")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.produtosSujeitosARecallInsegurosOuControlados")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.eVedadaAComercializacaoDe")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.produtosComRecallAtivo")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.itensConsideradosInsegurosPorAutoridades")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.equipamentosMedicosNaoHomologados")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.maquinasSemDispositivosDeSeguranca")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.produtosDependentesDeCertificacaoGovernamental")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.outrasCategoriasRestritas")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.incluemSeAindaEntreOutros")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.tabacoCigarrosEletronicosEDerivados")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.bebidasAlcoolicasEProdutosComRestricaoEtaria")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.animaisFloraEDerivados")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.veiculosIrregulares")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.ingressosParaEventos")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.alimentosEBebidasSemLicenca")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.pesticidasControlados")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.listasDeEMailEBasesDeDados")}</p>
        </li>
      </ul>
      <p>
        <em>{t("legal.pages.acceptableUsePolicy.blocks.produtosFisicosDeAltoRiscoOperacional")}</em>
      </p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.porDiretrizInternaDeRiscoLogisticaFraudeE")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.eletronicosCelularesNotebooksSmartwatchesConsoles")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.giftCardsECreditosDigitais")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.perfumesECosmeticos")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.eletrodomesticos")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.contasDigitaisOuAtivosVirtuais")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.produtosAmplamenteVisadosPorFraudeLogisticaOuChargeback")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.itensEAtividadesRestritosSujeitosAPreAprovacao")}</h3>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.dependemDeAnaliseDeRiscoEAutorizacaoExpressa")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.suplementosNutraceuticosEClaimsDeSaudeEmagrecimentoLibido")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.criptoAtivosDigitaisCustodiaOnOffRampNfts")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.ingressosEventosDoacoesCrowdfundingDentroDoPermitidoClubes")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.produtosReguladosComCertificacoesHomologacoesAnvisaAnatelInmetro")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.conteudoAdultoNaoExplicitoComModeracaoGatingEtario")}</p>
        </li>
      </ul>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.aAprovacaoPodeSerNegadaOuRevogadaA")}</p>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.requisitosMinimosDeTransparenciaComercial")}</h3>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.precoERecorrenciaExibirPeriodicidadeValorEData")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.consentimentoExpressoAntesDaPrimeiraCobrancaEDe")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.cancelamentoSimplesEPoliticaDeReembolsoVisivelEx")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.semDarkPatternsUrgenciasFalsasOmissoesRelevantes")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.claimsDeSaudeDesempenhoVerdadeirosVerificaveisESem")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.usosProibidosDeProdutosInfraDaMundpay")}</h3>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.dadosCadastraisFalsosIncompletosNaoInformarAlteracoesRelevantes")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.processarEmNomeDeOutroComercianteNaoIdentificado")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.usarAMundpayComoTerminalVirtualCardTester")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.usoDeMarcaLogosDaMundpaySemAutorizacao")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.medidasEConsequenciasEnforcement")}</h3>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.identificadaViolacaoOuRiscoMaterialAMundpayPodera")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.removerConteudosItensBloquearListagensIntegracoes")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.suspenderEncerrarContasEAcessos")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.reterValoresAplicarReservaDeRiscoLimitarSaques")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.exigirDocumentosECorrecoesLandingPageClaimsDisclosures")}</p>
        </li>
        <li>
          <p>{t("legal.pages.acceptableUsePolicy.blocks.notificarMarcasFornecedoresAfetadosParceirosDePagamentoE")}</p>
        </li>
      </ul>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.medidasFinanceirasRetencoesBloqueiosReservasSeguemOSeller")}</p>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.denunciaECanalDeContato")}</h3>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.suspeitouDeUsoIndevidoEnvieParaDenunciasMundpay")}</p>
      <h3>{t("legal.pages.acceptableUsePolicy.blocks.alteracoesEPrevalencia")}</h3>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.podemosAtualizarEstaPuaAQualquerTempoPublicando")}</p>
      <p>{t("legal.pages.acceptableUsePolicy.blocks.emCasoDeConflitoEntreEstaPuaE")}</p>
    </>
  );
}

export function AcceptableUsePolicyPage() {
  const { i18n } = useTranslation();
  const isPortuguese = i18n.resolvedLanguage?.toLowerCase().startsWith("pt");

  return (
    <LegalLayout>
      <LegalDocument>
        {isPortuguese ? <PortugueseLegalContent /> : <EnglishLegalContent />}
      </LegalDocument>
    </LegalLayout>
  );
}
