import { useTranslation } from "react-i18next";
import { LegalDocument } from "../LegalDocument";
import { LegalLayout } from "../LegalLayout";

export function GeneralComplianceProgramPage() {
  const { t } = useTranslation();

  return (
    <LegalLayout>
      <LegalDocument>
        <h1>{t("legal.pages.generalComplianceProgram.title")}</h1>
        <h2>{t("legal.pages.generalComplianceProgram.sections.appointment.title")}</h2>
        <ul>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.appointment.items.responsibility")}
            </p>
          </li>
        </ul>
        <ul>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.appointment.items.policies")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.appointment.items.focalPoint")}
            </p>
          </li>
        </ul>
        <h2>{t("legal.pages.generalComplianceProgram.sections.training.title")}</h2>
        <ul>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.training.items.regularTraining")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.training.items.topics")}
            </p>
          </li>
        </ul>
        <h2>{t("legal.pages.generalComplianceProgram.sections.monitoring.title")}</h2>
        <ul>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.monitoring.items.audits")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.monitoring.items.results")}
            </p>
          </li>
        </ul>
        <h2>{t("legal.pages.generalComplianceProgram.sections.reporting.title")}</h2>
        <ul>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.reporting.items.channels")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.reporting.items.protection")}
            </p>
          </li>
        </ul>
        <h2>{t("legal.pages.generalComplianceProgram.sections.investigation.title")}</h2>
        <ul>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.investigation.items.reports")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.investigation.items.measures")}
            </p>
          </li>
        </ul>
        <h2>{t("legal.pages.generalComplianceProgram.sections.review.title")}</h2>
        <ul>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.review.items.updates")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.generalComplianceProgram.sections.review.items.feedback")}
            </p>
          </li>
        </ul>
        <p>
          {t("legal.pages.generalComplianceProgram.closing")}
        </p>
      </LegalDocument>
    </LegalLayout>
  );
}
