import { useTranslation } from "react-i18next";

import { LegalDocument } from "../LegalDocument";
import { LegalLayout } from "../LegalLayout";

function EnglishLegalContent() {
  const { t } = useTranslation();

  return (
    <>
      <h1>{t("legal.pages.privacyPolicy.blocks.privacyPolicy")}</h1>
      <p>{t("legal.pages.privacyPolicy.blocks.atMundpayWeRespectYourPrivacyRegardingAny")}</p>
      <h3>{t("legal.pages.privacyPolicy.blocks.section1WhoWeAreAndToWhomThisPolicy")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.thisPolicyExplainsHowMundpayCollectsUsesShares")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.mundpayOperatesThroughTheseCompaniesDependingOnThe")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.mundpayInternationalPaymentsLtdCnpj55009285")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.mundUsaLlcEin3208193661160Heron")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.mundpayLlcEin365099929169MadisonAvenue")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.mundpTechOuReg17270502RuunaojaTn3")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.privacyPolicy.blocks.section2DataWeCollect")}</h3>
      <h4>
        <em>{t("legal.pages.privacyPolicy.blocks.section21DataProvidedByYou")}</em>
      </h4>
      <ul>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.accountContactDataNameEmailPhoneCountryState")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.purchaseDataItemsAmountsCurrencyTaxesOrderStatus")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.communicationAndSupportMessagesAttachmentsAndMetadataSent")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.customerAreaDataNecessaryToViewManageOrders")}</p>
        </li>
      </ul>
      <h4>
        <em>{t("legal.pages.privacyPolicy.blocks.section22DataCollectedAutomatically")}</em>
      </h4>
      <ul>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.deviceAndSessionInformationIpBrowserTypeVersion")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.usageLogsPagesAccessedDateTimeTrafficSource")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.cookiesAndSimilarTechnologiesPixelsTagsSdksFor")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.technicalSecuritySignalsAndFraudPreventionEG")}</p>
        </li>
      </ul>
      <h4>
        <em>{t("legal.pages.privacyPolicy.blocks.section23ThirdPartyData")}</em>
      </h4>
      <ul>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.paymentAntiFraudAnalysisAndInfrastructureProviders")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.logisticsPartnersForPhysicalProducts")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.suppliersBrandsStoresFromWhomYouPurchaseVia")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.privacyPolicy.blocks.section3PurposesOfProcessing")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.weUseTheDataFor")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.processingOrdersAndPaymentsIssuingInvoicesReceiptsAnd")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.deliveringProductsPhysicalOrDigitalActivatingLicensesAnd")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.securityAndAntiFraudDetectionOfMisuseDisputes")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.customerServiceAndCommunicationsSupportOrderNotificationsBilling")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.serviceImprovementAndAnalyticsUsageMetricsPerformanceUx")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.marketingWhenApplicableAndPermittedSendingOffersNews")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.privacyPolicy.blocks.section4CookiesPixelsAndPreferences")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.weUse")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.strictlyNecessaryLoginSecurityCartCheckout")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.performanceStatisticsEGAnalytics")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.functionalPreferences")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.advertisingWhenAdoptedByCampaignsThirdParties")}</p>
        </li>
      </ul>
      <p>{t("legal.pages.privacyPolicy.blocks.youCanManageCookiesInTheConsentBanner")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.disablingCertainCookiesMayLimitFunctionalities")}</p>
      <h3>{t("legal.pages.privacyPolicy.blocks.section5DataSharing")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.weSharePersonalDataOnlyWhenNecessary")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.mundpayGroupCompaniesSection1ForIntegratedOperation")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.providersAndProcessorsPaymentsAntiFraudCloudEmail")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.logisticsPartnersAndSuppliersStoresToFulfillThe")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.publicAuthoritiesWhenRequiredToFulfillLegalObligations")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.corporateEventsMergerAcquisitionReorganizationTransferOfData")}</p>
        </li>
      </ul>
      <p>{t("legal.pages.privacyPolicy.blocks.weDoNotSellPersonalDataIfIn")}</p>
      <h3>{t("legal.pages.privacyPolicy.blocks.section6InternationalTransfers")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.asWeOperateGloballyYourDataMayBe")}</p>
      <h3>{t("legal.pages.privacyPolicy.blocks.section7Retention")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.weKeepDataOnlyForAsLongAs")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.orderInvoicingRecordsAccordingToApplicableAccountingTax")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.technicalAndAntiFraudLogsReducedPeriodCompatible")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.marketingUntilUnsubscriptionOrMaximumInformedPeriod")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.privacyPolicy.blocks.section8YourControlsAndChoices")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.youCan")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.manageYourOrderAndSubscriptionAtOrderMundpay")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.adjustCommunicationPreferencesUnsubscribeFromPromotionalEmailsVia")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.setCookiesInTheBannerBrowser")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.requestAccessUpdateRemovalOfYourDataBy")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.privacyPolicy.blocks.section9ChildrenAndAdolescents")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.ourServicesAreNotIntendedForChildrenUnder")}</p>
      <h3>{t("legal.pages.privacyPolicy.blocks.section10Security")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.weAdoptAppropriateAdministrativeTechnicalAndPhysicalMeasures")}</p>
      <h3>{t("legal.pages.privacyPolicy.blocks.section11DoNotTrackAndInterestBasedAdvertising")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.someBrowsersOfferTheDoNotTrackDnt")}</p>
      <h3>{t("legal.pages.privacyPolicy.blocks.section12HowToExerciseRightsOrContactUs")}</h3>
      <ul>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.customerPortalOrderMundpayCom")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.privacySupportEmailHelpMundpayComPleaseIndicate")}</p>
        </li>
      </ul>
      <p>{t("legal.pages.privacyPolicy.blocks.corporateAddressesSeeSection1")}</p>
      <h3>{t("legal.pages.privacyPolicy.blocks.section13ChangesToThisPolicy")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.weMayUpdateThisPolicyToReflectOperational")}</p>
    </>
  );
}

function PortugueseLegalContent() {
  const { t } = useTranslation();

  return (
    <>
      <h1>{t("legal.pages.privacyPolicy.blocks.politicaDePrivacidade")}</h1>
      <p>{t("legal.pages.privacyPolicy.blocks.suaPrivacidadeEImportanteParaNos")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.ePoliticaDaMundpayRespeitarASuaPrivacidade")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.fazemosIssoPorMeiosJustosELegaisCom")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.tambemInformamosPorQueEstamosColetandoEssasInformacoes")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.quandoArmazenamosDadosProtegemosEssasInformacoesPorMeios")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.naoCompartilhamosPublicamenteInformacoesDeIdentificacaoPessoalCom")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.estejaCienteDeQueNaoTemosControleSobre")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.voceELivreParaRecusarNossaSolicitacaoDe")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.oUsoContinuoDoNossoSiteSeraConsiderado")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.seVoceTiverQualquerDuvidaSobreComoLidamos")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.oServicoGoogleAdsenseQueUtilizamosParaExibir")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.paraMaisInformacoesSobreOGoogleAdsenseConsulte")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.utilizamosAnunciosParaCompensarOsCustosOperacionaisDeste")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.osCookiesDePublicidadeComportamentalUtilizadosPorEste")}</p>
      <p>{t("legal.pages.privacyPolicy.blocks.diversosParceirosAnunciamEmNossoNomeEOs")}</p>
      <h3>{t("legal.pages.privacyPolicy.blocks.compromissoDoUsuario")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.oUsuarioSeComprometeAFazerUsoAdequado")}</p>
      <ul>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.aNaoSeEnvolverEmAtividadesIlegaisOu")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.bNaoDivulgarPropagandaOuConteudoDeNatureza")}</p>
        </li>
        <li>
          <p>{t("legal.pages.privacyPolicy.blocks.cNaoCausarDanosAosSistemasFisicosHardware")}</p>
        </li>
      </ul>
      <h3>{t("legal.pages.privacyPolicy.blocks.maisInformacoes")}</h3>
      <p>{t("legal.pages.privacyPolicy.blocks.esperamosQueIssoEstejaClaroEComoMencionado")}</p>
    </>
  );
}

export function PrivacyPolicyPage() {
  const { i18n } = useTranslation();
  const isPortuguese = i18n.resolvedLanguage?.toLowerCase().startsWith("pt");

  return (
    <LegalLayout>
      <LegalDocument>
        {isPortuguese ? <PortugueseLegalContent /> : <EnglishLegalContent />}
      </LegalDocument>
    </LegalLayout>
  );
}
