import { useTranslation } from "react-i18next";
import { LegalDocument } from "../LegalDocument";
import { LegalLayout } from "../LegalLayout";

export function ReportingChannelPage() {
  const { t } = useTranslation();

  return (
    <LegalLayout>
      <LegalDocument>
        <h1>{t("legal.pages.reportingChannel.title")}</h1>
        <h2>{t("legal.pages.reportingChannel.reports.title")}</h2>
        <p>
          {t("legal.pages.reportingChannel.reports.description")}
        </p>
        <h2>{t("legal.pages.reportingChannel.plagiarism.title")}</h2>
        <p>
          {t("legal.pages.reportingChannel.plagiarism.description")}
        </p>
        <h3>{t("legal.pages.reportingChannel.plagiarism.aboutYouTitle")}</h3>
        <ul>
          <li>
            <p>{t("legal.pages.reportingChannel.plagiarism.aboutYouItems.name")}</p>
          </li>
          <li>
            <p>{t("legal.pages.reportingChannel.plagiarism.aboutYouItems.email")}</p>
          </li>
          <li>
            <p>
              {t("legal.pages.reportingChannel.plagiarism.aboutYouItems.originalPlatform")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.reportingChannel.plagiarism.aboutYouItems.availableSince")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.reportingChannel.plagiarism.aboutYouItems.originalLinks")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.reportingChannel.plagiarism.aboutYouItems.ownershipProof")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.reportingChannel.plagiarism.aboutYouItems.previousSales")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.reportingChannel.plagiarism.aboutYouItems.comparativeMaterial")}
            </p>
          </li>
        </ul>
        <h3>{t("legal.pages.reportingChannel.plagiarism.copiedProductTitle")}</h3>
        <ul>
          <li>
            <p>
              {t("legal.pages.reportingChannel.plagiarism.copiedProductItems.illegalWebsite")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.reportingChannel.plagiarism.copiedProductItems.plagiarizedCheckout")}
            </p>
          </li>
          <li>
            <p>
              {t("legal.pages.reportingChannel.plagiarism.copiedProductItems.proof")}
            </p>
          </li>
        </ul>
        <p>
          {t("legal.pages.reportingChannel.plagiarism.details")}
        </p>
        <p>
          {t("legal.pages.reportingChannel.plagiarism.deadline")}
        </p>
        <h2>{t("legal.pages.reportingChannel.prohibitedProduct.title")}</h2>
        <p>
          {t("legal.pages.reportingChannel.prohibitedProduct.description")}
        </p>
        <h2>{t("legal.pages.reportingChannel.prohibitedProduct.productTitle")}</h2>
        <ul>
          <li>
            <p>{t("legal.pages.reportingChannel.prohibitedProduct.items.website")}</p>
          </li>
          <li>
            <p>{t("legal.pages.reportingChannel.prohibitedProduct.items.checkout")}</p>
          </li>
          <li>
            <p>{t("legal.pages.reportingChannel.prohibitedProduct.items.reason")}</p>
          </li>
          <li>
            <p>{t("legal.pages.reportingChannel.prohibitedProduct.items.proof")}</p>
          </li>
        </ul>
        <p>
          {t("legal.pages.reportingChannel.prohibitedProduct.details")}
        </p>
        <p>
          {t("legal.pages.reportingChannel.prohibitedProduct.deadline")}
        </p>
      </LegalDocument>
    </LegalLayout>
  );
}
