import { useTranslation } from "react-i18next";

import { LegalDocument } from "../LegalDocument";
import { LegalLayout } from "../LegalLayout";

function EnglishLegalContent() {
  const { t } = useTranslation();

  return (
    <>
      <h1>{t("legal.pages.termsOfUse.blocks.generalTermsOfUse")}</h1>
      <h2>{t("legal.pages.termsOfUse.blocks.generalAspects")}</h2>
      <h3>{t("legal.pages.termsOfUse.blocks.definitions")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.forPurposesOfTheseTermsOfUseThe")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.restrictedActivities")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.setOfActivitiesPracticesProductsOrServicesWhose")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.chargebackOrDispute")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.requestForCancellationReversalOrRefundOfA")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.seller")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.individualOrLegalEntityThatUsesTheMundpay")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.affiliate")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.individualOrLegalEntityThatWithTheSeller")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.user")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.comprehensiveTermDesignatingAnyIndividualOrLegalEntity")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.affiliateUser")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.individualOrLegalEntityThatPromotesPublicizesOr")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.buyerUser")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.individualOrLegalEntityThatAcquiresDigitalProducts")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.producerUser")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.individualOrLegalEntityThatCommercializesDigitalProducts")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.supplierUser")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.individualOrLegalEntityThatProvidesServicesLicenses")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.marketplace")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.digitalEnvironmentOperatedByAThirdPartyIn")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.platform")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.technologicalEnvironmentMadeAvailableAndOperatedByMundpay")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.restrictedActivitiesAndProhibitedActivities")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.setOfActivitiesProductsServicesOrPracticesProhibited")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.bankAccount")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.financialAccountOwnedByTheUserRegisteredAnd")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.feeOrCharge")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.remunerationOwedByTheUserToMundpayFor")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.taxes")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.taxObligationsApplicableToTheActivitiesCarriedOut")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.transaction")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.financialOperationInitiatedByTheBuyerAndProcessed")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.netBalance")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.amountAvailableToTheUserAfterAutomaticDeduction")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.securityReserveRollingReserve")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.amountRetainedByMundpayOnAPreventiveOr")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.payoutTransferSettlement")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.processByWhichMundpayTransfersToTheUser")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.reversalRefund")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.voluntaryOrCompulsoryReversalOfATransactionCarried")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.kycKnowYourCustomerAccountVerification")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.identificationAndDocumentaryValidationProceduresRequiredForAccount")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.suspiciousOperations")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.atypicalOrInconsistentMovementsWithTheUserS")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.maintenanceWindows")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.previouslyAnnouncedOrNecessaryPeriodsForUpdatesPerformance")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.scheduledUnavailability")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.temporaryServiceInterruptionDueToTechnicalOperationalOr")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.apiTechnologyIntegrator")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.programmingInterfaceProvidedByMundpayForIntegrationOf")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.applicabilityAndAcceptanceOfTerms")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.theseTermsOfUseApplyToAllWebsites")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.accessingBrowsingOrUsingAnyResourceOfThe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theseTermsGovernAccessToAndUseOf")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.scopeOfThePlatformAndServices")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.theseTermsOfUseConstituteALegallyBinding")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theMundpayGroupEntityActuallyEngagedByThe")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.unitedStates")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayLlcRegisteredUnderEinN365099929")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundUsaLlcRegisteredUnderEinN32")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.brazil")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayPagamentosInternacionaisLtdaRegisteredUnderCnpjNo")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.europe")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.mundpTechOuRegisteredUnderNo7270502With")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theIdentificationOfTheEntityResponsibleForProviding")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.supplementaryPolicies")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.theUserDeclaresToBeAwareOfAnd")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.suchPoliciesAreIncorporatedIntoTheseTermsFor")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theseTermsAndAnyEventualUpdatesSupersedeAnd")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.dataAndInformationProcessing")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.theUserDeclaresToBeAwareOfAnd2")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theUserAgreesThatDataMayBeShared")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.dataMayAlsoBeSharedWithPartiesDirectly")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayUndertakesToMaintainTheConfidentialityOfInformation")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theUserAcknowledgesThatInTheFaceOf")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theUserFurtherAcknowledgesThatAnyRepeatedDefault")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.nothingInThisInstrumentImpliesWaiverOfLegal")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.preservationOfRightsAndNonWaiver")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.anyEventualToleranceOmissionOrNonExerciseBy")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.anyEventualAndSpecificWaiverOfTheExercise")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.mundpaySActivity")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.theLegalRelationshipBetweenTheUserAndMundpay")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.byAcceptingTheTermsOfUseTheUser")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayOperatesExclusivelyAsAProviderOfTechnological")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.withRegardToOperationalModels")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.inBrazilMundpayOperatesPredominantlyAsAMarketplace")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.inTheUnitedStatesAndEuropeMundpayMay")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.ethocaAndVerifiAlertServices")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.theEthocaAndVerifiAlertServicesAffiliatedWith")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.suchServicesAreIntendedToMitigateRisksAnd")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theClientAcknowledgesAndAgreesThatAllTransactions")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theSaidFeeMayBeAdjustedAnnuallyIn")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.shouldTheClientExceedAChargebackRateOf")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.affiliateCompensationAndCpaPaymentConditions")}</h3>
      <h4>{t("legal.pages.termsOfUse.blocks.theAffiliateAcknowledgesAndAgreesThatTheirCompensation")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.iPercentageBasedRemunerationCalculatedOnTheValue")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.fixedCompensationCpaShallOnlyBeDisbursedOnce")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.untilSuchMinimumThresholdIsReachedCpaPayment")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.userRegistration")}</h2>
      <h3>{t("legal.pages.termsOfUse.blocks.userRegistrationAndEligibilityRequirements")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.individualsAndLegalEntitiesMeetingTheLegalRequirements")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.byAcceptingTheseTermsOfUseTheUser")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.buyerRegistrationMayBePerformedByPersonsAged")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayMayAtItsSoleDiscretionRefuseSuspend")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.userRegistrationAndAccessInformation")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.uponCompletingRegistrationOnThePlatformTheUser")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.registrationShallBeCarriedOutThroughTheCompletion")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.accessCredentialsAreStrictlyPersonalConfidentialAndNon")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.noEmployeeCollaboratorRepresentativeOrAgentOfMundpay")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.registrationAnalysisAndVerification")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.followingRegistrationCompletionTheInformationProvidedByThe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayMayAtAnyTimeAdoptAdditionalMeasures")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.accuracyOfInformation")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.uponRegistrationTheUserDeclaresAndWarrantsThat")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.registrationShallBeCompletedThroughAnElectronicForm")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.afterSubmissionOfRegistrationInformationItWillBe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.transparencyDutyToInformAndRelationshipWithThird")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.usersOfferingProductsOrServicesThroughThePlatform")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.thisInformationIncludesWithoutLimitationThoseRelatingTo")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theUserIsFullyResponsibleForActionsOr")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theUserIsSolelyResponsibleForMaintainingIts")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayMayAdoptCorrectivePreventiveOrSanctioningMeasures")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.politicallyExposedPersonsPep")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayDoesNotAcceptTheRegistrationActivationOr")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.forPurposesOfThisAgreementAPepIs")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.producerUsersAndAffiliatesDeclareThatTheyAre")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.producerUsersAndAffiliatesUndertakeToImmediatelyNotify")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theIdentificationAtAnyTimeOfPepClassification")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayMayConductPeriodicScreeningsAndRevalidationsIn")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.nonComplianceWithThisClauseConstitutesAMaterial")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.inTheEventOfInterpretiveConflictMundpayS")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.productAndServiceRegistration")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.productRegistrationPlatformUseAndProhibitedActivities")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theRegistrationAndCommercializationOfProductsAndServices")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.anyViolationOfTheProvisionsOfThisSection")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.productApprovalMayOccurAutomaticallyAndImmediatelyWhich")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.transparencyAdvertisingAndProductClaims")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.falseMisleadingOrPotentiallyErrorInducingClaimsAre")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.inTheCaseOfProductsRelatedToHealth")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.highRiskJurisdictionsAndPersons")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.inComplianceWithGuidelinesIssuedByInternationallyRecognized")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.highRiskJurisdictionsIncludeAmongOthersThoseSubject")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.prohibitedUsesOfMundpayProductsAndServices")}</h3>
      <h4>{t("legal.pages.termsOfUse.blocks.theUseOfThePlatformOrMundpayProducts")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.useOfFalseInaccurateManipulatedOrMisleadingData")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpaySConductIsGuidedByRespectFor")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.regularUseSecurityAndPlatformIntegrity")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theUserUndertakesToUseThePlatformIn")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theAdoptionOfAbusiveOrHarmfulDisclosurePractices")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.itIsAlsoProhibitedToPurchaseProductsThrough")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.disclosureAndIndependenceOfMundpay")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayMayAtItsSoleDiscretionMakeAvailable")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.intellectualPropertyProtection")}</h2>
      <h3>{t("legal.pages.termsOfUse.blocks.mundpay")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.allIntellectualPropertyRightsRelatedToMundpayAre")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.accessToAndUseOfThePlatformDo")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theReproductionModificationAdaptationTranslationDistributionPublicationDisplay")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.recognitionOfOwnershipDomainAndVisualIdentity")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theUserAcknowledgesThatTheDomainNameS")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpaySafeguardsItsRightsBasedOnGoodFaith")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.trademarkUseAndImproperAssociation")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.theUseOfMundpaySTrademarksLogosTrade")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.nonExistentCommercialAssociation")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.partnershipCertificationOrEndorsement")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.corporateOrInstitutionalTies")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.productApprovalOrEndorsement")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.anyUseRequiresPriorExpressAndWrittenAuthorization")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.licenseOfUseGrantedByUsersToMundpay")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.usersWhoRegisterProductsOrContentDeclareThat")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theLicenseDoesNotImplyTransferOfOwnership")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.prohibitionOfUnfairCompetition")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.theUserUndertakesNotToEngageInActs")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.usingFraudulentMeansToDivertForTheirOwn")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.usingOrImitatingExpressionsAdvertisingSignsVisualIdentity")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.improperlyUsingMundpaySTradeNameEstablishmentTitle")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.producingDisseminatingOrBroadcastingContentThatMisleadsThe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.suchConductWillBeConsideredSeriousContractualViolations")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.prohibitionOfParasitismAndImproperDomainUse")}</h3>
      <h4>{t("legal.pages.termsOfUse.blocks.itIsExpresslyProhibitedForTheUserTo")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.registerDomainNamesIdenticalOrSimilarToThose")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.usePhoneticOrthographicOrVisualVariationsThatMay")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.createProfilesOnSocialNetworksWithConfusinglySimilar")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.useTheMundpayTrademarkOrVariationsInSponsored")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.engageInBrandBiddingCybersquattingTyposquattingOrAny")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.parasitismIsUnderstoodAsTheImproperExploitationOf")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.penaltiesForViolation")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.violationOfTheProvisionsRelatingToIntellectualProperty")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.immediateAccountSuspension")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.blockingOfFeatures")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.fundRetention")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.contentRemoval")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.contractTerminationForJustCause")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.withoutPrejudiceToTheAboveTheOffenderShall")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.usersAndThirdParties")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.copyrightsConstituteLegalProtectionGrantedToOriginalWorks")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.elementsSuchAsNamesTitlesAndSlogansAre")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.inThisRegardTheProducerUponRegisteringAny")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.itShouldBeNotedThatTheAvailabilityOf")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.liabilityForThirdPartyRights")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.usersAreFullyResponsibleForEnsuringThatProducts")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.inTheEventOfInfringementMundpayMayRemove")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.channelForNotificationOfCopyrightInfringement")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.theProducerWhoSuspectsInfringementOfTheirCopyright")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.likewiseAnyUserWhoIdentifiesAViolationOf")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.uponReceiptOfTheNotificationMundpayWillConduct")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayDoesNotAcceptComplaintsFromThirdParties")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.bySubmittingTheComplaintTheComplainantDeclaresTo")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.formalRequirementsForNotification")}</h3>
      <h4>{t("legal.pages.termsOfUse.blocks.forAdequateDocumentationOfTheComplaintItIs")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.declarationContainingTheElectronicOrPhysicalSignatureOf")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.descriptionOfTheCopyrightedWorkAllegedToHave")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.preciseIndicationOfTheLocationOfTheInfringing")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.addressPhoneNumberAndEmailForContact")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.goodFaithDeclarationThatTheMaterialUseWas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.declarationOfTruthfulnessOfTheInformationProvidedUnder")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.preliminaryBlockingOrSuspensionMeasures")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.whenItDeemsThereToBeAnEmergency")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.inSuchCasesTheRespondentShallHaveNo")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theProducerWhoseInfoproductHasBeenBlockedShall")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.refunds")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.refundRequestsMayBeFormalizedByTheBuyer")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayRegardlessOfPriorConsultationOrConsentFrom")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.suchPrerogativeMayBeExercisedIncludingWhenThe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.likewiseMundpayMayProceedWithTheRefundIf")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theMeasureMayAlsoBeAdoptedWhenEvidence")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.finallyMundpayMayProceedWithARefundWhen")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.chargebacks")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayAsAPaymentIntermediaryAndParticipantIn")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.inThisContextItReservesTheRightTo")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theRetentionPercentageMayBeRevisedAndIncreased")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theAdoptionOfARetroactiveReserveIsIntended")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theRetentionPeriodMayAlsoBeExtendedWhen")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.whenEvidenceOfSuspiciousFraudulentOrHighlyLikely")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.likewiseIfTransactionDataLinkedToTheSeller")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.onceTheChargebackIsFormallyReportedByThe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theSellerMayBeGrantedAtMundpayS")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.forThePurposeOfDocumentingTheDefenseThe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.proofOfProductDeliveryOrServiceAvailabilityIncluding")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.logisticalProofWithAValidTrackingCodeMovement")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.electronicRecordsOfPurchaseAcceptanceAuthenticationOrValidation")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.evidenceOfTheBuyerSActiveParticipationIn")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.copiesOfCommunicationsHeldWithTheBuyerSuch")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.proofOfAccessConsumptionOrEnjoymentOfThe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.commercialPoliciesInEffectAtTheTimeOf")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.anyOtherAdditionalDocumentsOrEvidenceRequestedBy")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.failureToSubmitDocumentationWithinTheStipulatedPeriod")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.itShouldBeNotedThatTheAnalysisAnd")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.failureToTimelySubmitTheRequestedDocumentsOr")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theProducerUndertakesToMaintainAdequateAfterSales")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.thePlatformMayWithoutPriorConsentConductDispute")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.forOperationalAndRiskManagementPurposesAChargeback")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.ifThisThresholdIsExceededMundpayMayAt")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.withoutPrejudiceTheIdentificationOfConductViolatingApplicable")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.suchMeasureIsIntendedToProtectTheIntegrity")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.uponImplementationOfTheBlockTheUserWill")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.inTheEventOfContractTerminationFundWithdrawal")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.finallyMundpayMayApplyAPreChargebackMechanism")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.uponIdentificationOfARiskAlertMundpayMay")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.accountSuspensionBlockingAndDeletion")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.penaltiesApplicableAsAResultOfMisuseOf")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.examplesOfGroundsForImposingPenaltiesIncludeThe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.measuresMayBeAppliedWithOrWithoutPrior")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theRemovalOfProductsOrClosureOfAccounts")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.uponNotificationOfAChargebackMundpayWillImmediately")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.failureToSubmitDocumentationOrAnUnfavorableDecision")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.suspension")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.suspensionIsAPreventiveAndTemporaryMeasureApplied")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.inCasesOfSuspectedFraudSuspensionMayBe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.duringTheSuspensionAdditionalRiskMitigationMeasuresMay")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.blocking")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.blockingConstitutesAMoreSevereMeasureApplicableWhen")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayShallBlockAndRetainFundsArisingFrom")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.furthermoreTheBlockingShallBeAutomaticallyTriggeredOnce")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.ifAcquirersProcessorsOrFinancialInstitutionsOrderBlocks")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.whenEvidenceOfAMaterialIncreaseInThe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.ifTheTaxpayerIdentificationNumberLinkedToThe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.suchFundsShallRemainWithheldUntilProperRegularization")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.deletion")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.deletionImpliesTheDefinitiveClosureOfTheAccount")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.uponConfirmedFraudTheAccountMayBeBlocked")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.uponRecognitionOfAViolationSubjectToDeletion")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.uponCompletionOfDeletionOrEarlyTerminationOf")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.complaintAndInternalInvestigation")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayMayInitiateInvestigationProceedingsUponComplaintsFrom")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.ifConsideredPlausibleMundpayMayAdoptPreliminaryMeasures")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.whenTheDisputeInvolvesAConflictBetweenUsers")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.investigationsMayBeInitiatedAtAnyTimeAnd")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.fees")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.theUserAcknowledgesAndAgreesThatAnyFees")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theUserFurtherAcknowledgesThatTheFeesApplicable")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.continuedUseOfThePlatformFollowingTheImplementation")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.minimumWithdrawalThreshold")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.withdrawalsOnThePlatformAreSubjectToMinimum")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.forAccountsOperatingExclusivelyWithinBrazilianTerritoryThe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theApplicableAmountsShallBeClearlyDisclosedWithin")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayReservesTheRightToReviewAmendOr")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.mundpaySLiabilityExclusionsAndLimitations")}</h2>
      <h3>{t("legal.pages.termsOfUse.blocks.natureOfServices")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.theServicesFeaturesInformationContentSystemsSoftwareMaterials")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayDoesNotGuaranteeThatThePlatformWill")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.absenceOfWarranties")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.toTheMaximumExtentPermittedByApplicableLaw")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theUserAcknowledgesAndAgreesThatUseOf")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.limitationOfScopeOfActivity")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayOperatesExclusivelyAsAProviderOfTechnological2")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theProductsServicesContentOffersAndInformationMade")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.exclusionOfLiability")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.exceptInCasesOfObjectiveOrMandatoryLiability")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.mundpayShallNotBeResponsibleByWayOf")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.theInadequacyQualityQuantityDefectsFlawsRisksOr")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.falseIncompleteInaccurateOrMisleadingInformationProvidedBy")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.nonComplianceWithLegalOrContractualObligationsAssumed")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.deadlinesDeliveryMethodsExchangesReturnsLossesOrCancellations")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.reversalsRefundsChargebacksRefusalsBlocksOrTransactionReversals")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.technicalFailuresUnavailabilityInterruptionsCyberattacksVirusesConnectivityFailures")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.misuseOfThePlatformByThirdPartiesIncluding")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.contentServicesInformationOrMaterialsMadeAvailableIn")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.ancillaryServicesProvidedByThirdPartiesIncludingCurrency")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.thirdPartyServices")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.thePlatformMayContainIntegrationsLinksOrAccess")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.noPromiseOfResults")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayDoesNotPromiseGuaranteeOrEnsureAny")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.regulatoryCompliancePoliciesAndSanctions")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.inComplianceWithNationalAndInternationalStandardsFor")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.limitationOfIndemnifiableAmount")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.inTheEventOfMundpaySLiabilityThis")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.userAcknowledgment")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.theUserAcknowledgesThatTheLiabilityExclusionAnd")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.supportChannelsAndHours")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.forQuestionsComplaintsOrSuggestionsTheUserMay")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.finalProvisions")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.theUserIsProhibitedFromAssigningTransferringOr")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.rightOfRecourseAndIndemnificationOfMundpay")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.byAcceptingTheseTermsOfUseTheUser2")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theObligationToIndemnifyIncludesWithoutLimitationExpenses")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theUserAlsoUndertakesToHoldHarmlessAnd")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.anyEventualToleranceByEitherPartyRegardingNon")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.inTheEventThatJudicialOrExtrajudicialMeasures")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.consensualResolutionOfDisputes")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.thePartiesUndertakeToMakeTheirBestEfforts")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.jurisdiction")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.thePartiesElectTheCourtsOfTheComarca")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.applicableLaw")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.theseTermsOfUseAndTheLegalRelationship")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.disputeResolution")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.disputesArisingFromOrRelatedToTheseTerms")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.arbitrationShallConstituteTheExclusiveForumForDispute")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theArbitralProceedingsShallBeConductedInAccordance")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.unlessOtherwiseAgreedByThePartiesHearingsShall")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.costsAdministrativeFeesAndArbitralFeesShallFollow")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theArbitratorMayGrantDeclaratoryOrInjunctiveRelief")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.anExpressWaiverToParticipateInClassActions")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.forPurposesOfApplicableSubstantiveLawThisAgreement")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.theChoiceOfArbitrationDoesNotPrecludeAs")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.filingClaimsBeforeSmallClaimsCourtsWhenThe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.seekingPreliminaryInjunctionsOrUrgentReliefBeforeThe")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.rightToOptOutOfArbitration")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.notwithstandingTheMandatoryArbitrationProvidedForInThis")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.toValidlyExerciseTheOptOutTheUser")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.theNoticeMustContainAtAMinimum")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.fullNameOrCorporateName")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.registeredAddress")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.emailLinkedToTheAccount")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.accountIdentifierOrMerchantId")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.expressDeclarationOfRefusalOfTheMandatoryArbitration")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theNoticeMustBeSentToTheContractual")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.failureToExerciseTheOptOutRightWithin")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.theExerciseOfTheOptOutShallNot")}</p>
    </>
  );
}

function PortugueseLegalContent() {
  const { t } = useTranslation();

  return (
    <>
      <h1>{t("legal.pages.termsOfUse.blocks.termosGeraisDeUso")}</h1>
      <h2>{t("legal.pages.termsOfUse.blocks.aspectosGerais")}</h2>
      <h3>{t("legal.pages.termsOfUse.blocks.definicoes")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.paraFinsDestesTermosDeUsoAsExpressoes")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.atividadesRestritas")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.conjuntoDeAtividadesPraticasProdutosOuServicosCuja")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.chargebackOuContestacao")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.solicitacaoDeCancelamentoEstornoOuReembolsoDeUma")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.usuario")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.termoAbrangenteQueDesignaQualquerPessoaFisicaOu")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.usuarioVendedor")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.pessoaFisicaOuJuridicaQueUtilizaAPlataforma")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.usuarioAfiliado")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.pessoaFisicaOuJuridicaQueMedianteAutorizacaoDo")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.usuarioComprador")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.pessoaFisicaOuJuridicaQueAdquireProdutosDigitais")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.usuarioProdutor")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.pessoaFisicaOuJuridicaQueComercializaProdutosDigitais")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.marketplace")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.ambienteDigitalOperadoPorTerceiroNoQualDiferentes")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.plataforma")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.ambienteTecnologicoDisponibilizadoEOperadoPelaMundpayComposto")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.atividadesRestritasEAtividadesProibidas")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.conjuntoDeAtividadesProdutosServicosOuPraticasProibidas")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.contaBancaria")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.contaFinanceiraDeTitularidadeDoUsuarioCadastradaE")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.tarifaOuTaxa")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.remuneracaoDevidaPeloUsuarioAMundpayPelosServicos")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.tributos")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.obrigacoesTributariasIncidentesSobreAsAtividadesExercidasPelo")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.transacao")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.operacaoFinanceiraIniciadaPeloCompradorEProcessadaPela")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.saldoLiquido")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.montanteDisponivelAoUsuarioAposADeducaoAutomatica")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.reservaDeSegurancaRollingReserve")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.montanteRetidoPelaMundpayDeFormaPreventivaOu")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.payoutRepasseLiquidacao")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.processoPeloQualAMundpayTransfereAoUsuario")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.estornoRefund")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.reversaoVoluntariaOuCompulsoriaDeUmaTransacaoRealizada")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.kycKnowYourCustomerVerificacaoDeConta")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.procedimentosDeIdentificacaoEValidacaoDocumentalExigidosPara")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.operacoesSuspeitas")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.movimentacoesAtipicasOuIncompativeisComOPerfilDo")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.janelasDeManutencao")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.periodosPreviamenteInformadosOuNecessariosParaAtualizacoesMelhorias")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.indisponibilidadeProgramada")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.interrupcaoTemporariaDosServicosPorNecessidadeTecnicaOperacional")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.apiIntegradorTecnologico")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.interfaceDeProgramacaoDisponibilizadaPelaMundpayParaIntegracao")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.aplicabilidadeEAceitacaoDosTermos")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.estesTermosDeUsoAplicamSeATodos")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oAcessoNavegacaoOuUtilizacaoDeQualquerRecurso")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.estesTermosRegulamOAcessoEOUso")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.escopoDaPlataformaEDosServicos")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.estesTermosDeUsoConstituemUmContratoJuridicamente")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aEmpresaDoGrupoMundpayEfetivamenteContratadaPelo")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.estadosUnidos")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayLlcInscritaSobOEinN36")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.mundUsaLlcInscritaSobOEinN")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.brasil")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.mundpayPagamentosInternacionaisLtdaInscritaNoCnpjN")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.europa")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.mundpTechOuRegistradaSobON7270502")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aIdentificacaoDaEntidadeResponsavelPelaPrestacaoDos")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.politicasComplementares")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioDeclaraEstarCienteEDeAcordo")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.taisPoliticasIntegramEstesTermosParaTodosOs")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.estesTermosESuasEventuaisAtualizacoesSubstituemE")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.tratamentoDeDadosEInformacoes")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioDeclaraEstarCienteEAutorizaExpressamente")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioConcordaQueOsDadosPossamSer")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.osDadosTambemPoderaoSerCompartilhadosComPartes")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayComprometeSeAManterAConfidencialidade")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioReconheceQueDianteDeRiscosDe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioReconheceTambemQueAEventualReiteracao")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.nadaNesteInstrumentoImplicaRenunciaADireitosLegais")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.preservacaoDeDireitosENaoRenuncia")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aEventualToleranciaOmissaoOuNaoExercicioPela")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aRenunciaEventualEEspecificaAoExercicioDe")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.daAtividadeDaMundpay")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aRelacaoJuridicaEntreOUsuarioEA")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aoAderirAosTermosDeUsoOUsuario")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayAtuaExclusivamenteComoPrestadoraDeServicos")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.noQueSeRefereAosModelosOperacionais")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.noBrasilAMundpayAtuaPredominantementeComoMarketplace")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.nosEstadosUnidosENaEuropaAMundpay")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.dosServicosDeAlertaEthocaEVerifi")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.osServicosDeAlertaEthocaEVerifiAfiliadas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.taisServicosTemPorFinalidadeAMitigacaoDe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oClienteDeclaraCienciaEConcordanciaDeQue")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oValorDaReferidaTaxaPoderaSerReajustado")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.casoOClienteUltrapasseOIndiceDe1")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.daRemuneracaoDoAfiliadoECondicoesParaPagamento")}</h3>
      <h4>{t("legal.pages.termsOfUse.blocks.oAfiliadoDeclaraEstarCienteDeQueSua")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.iRemuneracaoPercentualCalculadaSobreOValorDas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oRecebimentoDaRemuneracaoFixaCpaSomenteSera")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.enquantoReferidoPatamarMinimoNaoForAtingidoO")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.doCadastroDoUsuario")}</h2>
      <h3>{t("legal.pages.termsOfUse.blocks.doCadastroDoUsuarioERequisitosDeElegibilidade")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.poderaoSeCadastrarComoUsuariosDaPlataformaMundpay")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aoAceitarEstesTermosDeUsoOUsuario")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oCadastroDeCompradoresPoderaSerRealizadoPor")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayPoderaASeuExclusivoCriterioRecusar")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.dasInformacoesCadastraisEDeAcessoDoUsuario")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aoRealizarOCadastroNaPlataformaOUsuario")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oCadastroSeraRealizadoMedianteOPreenchimentoDe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.asCredenciaisDeAcessoSaoPersonalissimasConfidenciaisE")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.nenhumEmpregadoColaboradorRepresentanteOuAgenteDaMundpay")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.daAnaliseEVerificacaoCadastral")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aposAConclusaoDoCadastroAsInformacoesFornecidas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayPoderaAQualquerTempoAdotarMedidas")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.daVeracidadeDasInformacoes")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aoRealizarOCadastroOUsuarioDeclaraE")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oCadastroSeraEfetuadoMedianteOPreenchimentoDe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aposOEnvioDasInformacoesCadastraisEstasEstarao")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.daTransparenciaDeverDeInformacaoERelacaoCom")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.osUsuariosQueOfertaremProdutosOuServicosPor")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.essasInformacoesIncluemSemLimitacaoAquelasRelativasA")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioEIntegralmenteResponsavelPorAcoesOu")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.eDeExclusivaResponsabilidadeDoUsuarioVendedorManter")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayPoderaAdotarMedidasCorretivasPreventivasOu")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.daPessoaExpostaPoliticamentePep")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayNaoAceitaOCadastroAAtivacao")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.paraFinsDesteAcordoPepETodaPessoa")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.osUsuariosProdutoresEAfiliadosDeclaramNaoSer")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.osUsuariosProdutoresEAfiliadosComprometemSeA")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aConstatacaoAQualquerTempoDeEnquadramentoPep")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayPoderaRealizarTriagensERevalidacoesPeriodicas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oDescumprimentoDestaClausulaConfiguraInfracaoMaterialOs")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.emCasoDeConflitoInterpretativoPrevaleceAPolitica")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.doCadastroDeProdutosEServicos")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.doCadastroDeProdutosUsoDaPlataformaE")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oCadastroEAComercializacaoDeProdutosE")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aOcorrenciaDeQualquerViolacaoAsDisposicoesDeste")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aAprovacaoDeProdutosPoderaOcorrerDeForma")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.transparenciaPublicidadeEAlegacoesSobreProdutos")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.eExpressamenteProibidaARealizacaoDeAlegacoesFalsas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.noCasoDeProdutosRelacionadosASaudeBem")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.jurisdicoesEPessoasDeAltoRisco")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.emAtencaoADiretrizesExpedidasPorOrgaosDe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.saoConsideradasJurisdicoesDeAltoRiscoEntreOutras")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.usosProibidosDosProdutosEServicosDaMundpay")}</h3>
      <h4>{t("legal.pages.termsOfUse.blocks.eVedadoOUsoDaPlataformaOuDos")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.utilizacaoDeDadosFalsosImprecisosManipuladosOuEnganosos")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayPautaSuaAtuacaoPeloRespeitoAos")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.usoRegularSegurancaEIntegridadeDaPlataforma")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioComprometeSeAUtilizarAPlataforma")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.eProibidaAAdocaoDePraticasAbusivasOu")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.tambemEVedadoAdquirirProdutosPorMeioDo")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.divulgacaoEIndependenciaDaMundpay")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayPoderaASeuExclusivoCriterioDisponibilizar")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.daProtecaoAPropriedadeIntelectual")}</h2>
      <h3>{t("legal.pages.termsOfUse.blocks.daMundpay")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.todosOsDireitosDePropriedadeIntelectualRelacionadosA")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oAcessoEAUtilizacaoDaPlataformaNao")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.eExpressamenteVedadoReproduzirModificarAdaptarTraduzirDistribuir")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.reconhecimentoDeTitularidadeDominioEIdentidadeVisual")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioReconheceQueOSNomeS")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayResguardaSeusDireitosComFundamentoNo")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.usoDeMarcaEAssociacaoIndevida")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.eProibidaAUtilizacaoDeMarcasLogotiposNomes")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.associacaoComercialInexistente")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.parceriaCertificacaoOuHomologacao")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.vinculoSocietarioOuInstitucional")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aprovacaoOuEndossoDeProdutos")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.qualquerUsoDependeraDeAutorizacaoPreviaExpressaE")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.licencaDeUsoConcedidaPelosUsuariosAMundpay")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.osUsuariosQueCadastraremProdutosOuConteudosDeclaram")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aLicencaNaoImplicaTransferenciaDeTitularidadePermanecendo")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.vedacaoAConcorrenciaDesleal")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioComprometeSeANaoPraticarAtos")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.empregarMeiosFraudulentosParaDesviarEmProveitoProprio")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.utilizarOuImitarExpressoesSinaisDePropagandaIdentidade")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.usarIndevidamenteNomeComercialTituloDeEstabelecimentoDominio")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.produzirDivulgarOuVeicularConteudosQueInduzamO")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.taisCondutasSeraoConsideradasInfracoesContratuaisGravesSem")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.proibicaoDeParasitismoEUsoIndevidoDeDominio")}</h3>
      <h4>{t("legal.pages.termsOfUse.blocks.eExpressamenteVedadoAoUsuario")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.registrarNomesDeDominioIdenticosOuSimilaresAos")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.utilizarVariacoesFoneticasOrtograficasOuVisuaisQuePossam")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.criarPerfisEmRedesSociaisComDenominacoesConfundiveis")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.utilizarAMarcaMundpayOuVariacoesEmAnuncios")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.praticarBrandBiddingCybersquattingTyposquattingOuQuaisquerFormas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.consideraSeParasitismoOAproveitamentoIndevidoDaReputacao")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.penalidadesPorViolacao")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aViolacaoDasDisposicoesRelativasAPropriedadeIntelectual")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.suspensaoImediataDaConta")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.bloqueioDeFuncionalidades")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.retencaoDeValores")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.remocaoDeConteudos")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.rescisaoContratualPorJustaCausa")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.semPrejuizoDissoOInfratorFicaraSujeitoA")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.dosUsuariosETerceiros")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.osDireitosAutoraisConstituemProtecaoLegalConferidaA")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.elementosComoNomesTitulosESlogansEmRegra")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.nesseSentidoOProdutorAoCadastrarQualquerProduto")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.ressaltaSeQueADisponibilizacaoDoProdutoNa")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.responsabilidadePorDireitosDeTerceiros")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.osUsuariosSaoIntegralmenteResponsaveisPorAssegurarQue")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.naHipoteseDeInfracaoAMundpayPoderaRemover")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.canalParaNotificacaoDeViolacaoDeDireitosAutorais")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.oProdutorQueSuspeitarDeViolacaoDeSeus")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.daMesmaFormaQualquerUsuarioQueIdentificarViolacao")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aposORecebimentoDaNotificacaoAMundpayRealizara")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayNaoAceitaReclamacoesFormuladasPorTerceiros")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aoEncaminharAReclamacaoOReclamanteDeclaraSe")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.requisitosFormaisDaNotificacao")}</h3>
      <h4>{t("legal.pages.termsOfUse.blocks.paraAdequadaInstrucaoDaReclamacaoRecomendaSeQue")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.declaracaoContendoAssinaturaEletronicaOuFisicaDoTitular")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.descricaoDoTrabalhoProtegidoPorDireitoAutoralQue")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.indicacaoPrecisaDaLocalizacaoDoMaterialInfratorNa")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.enderecoTelefoneEEMailParaContato")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.declaracaoDeBoaFeQuantoANaoAutorizacao")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.declaracaoDeVeracidadeDasInformacoesPrestadasSobAs")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.medidasLiminaresDeBloqueioOuSuspensao")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.quandoEntenderPresenteSituacaoDeUrgenciaOuRisco")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.nessasHipotesesNaoHaveraDireitoAQualquerEspecie")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.seraAsseguradoAoProdutorQueTeveSeuInfoproduto")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.doReembolso")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.osPedidosDeReembolsoPoderaoSerFormalizadosPelo")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayIndependentementeDePreviaConsultaOuAnuencia")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.talPrerrogativaPoderaSerExercidaInclusiveQuandoO")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.daMesmaFormaAMundpayPoderaEfetivarO")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMedidaTambemPoderaSerAdotadaQuandoVerificados")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.porFimAMundpayPoderaProcederComO")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.dosChargebacks")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayNaQualidadeDeIntermediadoraDePagamentos")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.nesseContextoReservaSeODireitoDeReter")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oPercentualDeRetencaoPoderaSerRevistoE")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aAdocaoDeReservaRetroativaTemPorFinalidade")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oPrazoDeRetencaoPoderaAindaSerEstendido")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.verificadosIndiciosDeTransacoesSuspeitasFraudulentasOuCom")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.deIgualModoConstatandoSeQueDadosDe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.umaVezFormalmenteNoticiadoOChargebackPelosInstituidores")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.poderaSerAsseguradoAoVendedorAExclusivoCriterio")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.paraFinsDeInstrucaoDaDefesaPoderaoSer")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.comprovacaoDeEntregaDoProdutoOuDisponibilizacaoDo")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.comprovacaoLogisticaComCodigoDeRastreioValidoHistorico")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.registrosEletronicosDeAceiteAutenticacaoOuValidacaoDa")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.evidenciasDaParticipacaoAtivaDoCompradorNaContratacao")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.copiasDeComunicacoesMantidasComOCompradorTais")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.comprovacaoDeAcessoConsumoOuFruicaoDoProduto")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.politicasComerciaisVigentesAEpocaDaVendaEspecialmente")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.quaisquerOutrosDocumentosOuEvidenciasAdicionaisSolicitadasPela")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oNaoEnvioDaDocumentacaoNoPrazoEstipulado")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.ressaltaSeQueAAnaliseEDecisaoAcerca")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aNaoApresentacaoTempestivaDosDocumentosSolicitadosOu")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oProdutorComprometeSeAManterAdequadoSuporte")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aPlataformaPoderaIndependentementeDeAnuenciaPreviaConduzir")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.paraFinsDeParametroOperacionalEGestaoDe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aSuperacaoDessePatamarAutorizaAMundpayA")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.semPrejuizoAVerificacaoDeCondutasQueViolem")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.talMedidaVisaResguardarAIntegridadeDoArranjo")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.efetivadoOBloqueioOUsuarioSeraNotificadoPelos")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.emCasoDeRescisaoContratualLevantamentoDeValores")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.porFimAMundpayPoderaAplicarMecanismoDe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.umaVezIdentificadoOAlertaDeRiscoA")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.daSuspensaoBloqueioEExclusaoDaContaDo")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.constituemPenalidadesAplicaveisEmDecorrenciaDoUsoIndevido")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.saoConsideradasCausasExemplificativasParaAplicacaoDasPenalidades")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.asMedidasPoderaoSerAplicadasComOuSem")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aRemocaoDeProdutosOuEncerramentoDeContas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.quandoNotificadoChargebackAMundpayDebitaraImediatamenteO")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aNaoApresentacaoDosDocumentosOuDecisaoDesfavoravel")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.daSuspensao")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aSuspensaoConsisteEmMedidaPreventivaETemporaria")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.emCasoDeSuspeitaDeFraudeASuspensao")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.duranteASuspensaoPoderaoSerAdotadasMedidasAdicionais")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.doBloqueio")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.oBloqueioConfiguraMedidaMaisGravosaEProtetiva")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayProcederaAoBloqueioEARetencao")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.adicionalmenteOBloqueioSeraAutomaticamenteAplicadoAPartir")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.casoAdquirentesProcessadorasOuInstituicoesFinanceirasDeterminemBloqueios")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.verificadosIndiciosDeAumentoRelevanteDoIndiceDe")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.constatadoQuePessoaFisicaMenorDeIdadeMenor")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.casoOCnpjVinculadoAContaNaPlataforma")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.daExclusao")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aExclusaoImplicaOEncerramentoDefinitivoDaConta")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.confirmadaFraudeAContaPoderaSerBloqueadaE")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.reconhecidaInfracaoSujeitaAExclusaoAMundpayApresentara")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.efetivadaAExclusaoOuRescisaoAntecipadaDaRelacao")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.daDenunciaEAveriguacaoInterna")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayPoderaInstaurarProcedimentosDeAveriguacaoMediante")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.sendoConsideradaVerossimilAMundpayPoderaAdotarMedidas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.quandoAControversiaEnvolverConflitoEntreUsuariosA")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.asAveriguacoesPoderaoSerIniciadasAQualquerTempo")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.dasTaxas")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioReconheceEConcordaQueAsTaxas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioDeclaraAindaEstarCienteDeQue")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aPermanenciaEAContinuidadeDoUsoDa")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.limiteMinimoParaSolicitacaoDeSaques")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aRealizacaoDeSaquesNaPlataformaEstaCondicionada")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.paraContasOperandoExclusivamenteNoTerritorioBrasileiroO")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.osValoresAplicaveisEstaraoDevidamenteDiscriminadosNoPainel")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayReservaSeODireitoDeRevisar")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.isencaoELimitesAResponsabilizacaoDaMundpay")}</h2>
      <h3>{t("legal.pages.termsOfUse.blocks.naturezaDosServicos")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.osServicosFuncionalidadesInformacoesConteudosSistemasSoftwaresMateriais")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayNaoAsseguraQueAPlataformaEstara")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.ausenciaDeGarantias")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.naMaximaExtensaoPermitidaPelaLegislacaoVigenteA")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioReconheceEConcordaQueAUtilizacao")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.limitacaoDoEscopoDeAtuacao")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayAtuaExclusivamenteComoProvedoraDeInfraestrutura")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.osProdutosServicosConteudosOfertasEInformacoesDisponibilizados")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.exclusaoDeResponsabilidade")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.ressalvadasAsHipotesesDeResponsabilidadeObjetivaOuImperativa")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.aMundpayNaoSeraResponsavelExemplificativamentePorDanos")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.daInadequacaoQualidadeQuantidadeViciosDefeitosRiscosOu")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.deInformacoesFalsasIncompletasImprecisasOuEnganosasFornecidas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.doDescumprimentoDeObrigacoesLegaisOuContratuaisAssumidas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.dePrazosFormasDeEntregaTrocasDevolucoesExtravios")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.deEstornosReembolsosChargebacksRecusasBloqueiosOuReversoes")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.deFalhasTecnicasIndisponibilidadesInterrupcoesAtaquesCiberneticosVirus")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.doUsoIndevidoDaPlataformaPorTerceirosInclusive")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.deConteudosServicosInformacoesOuMateriaisDisponibilizadosEm")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.deServicosAuxiliaresPrestadosPorTerceirosIncluindoConversao")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.servicosDeTerceiros")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aPlataformaPoderaConterIntegracoesLinksOuAcessos")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.inexistenciaDePromessasDeResultado")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aMundpayNaoPrometeGaranteOuAsseguraQualquer")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.dasPoliticasDeConformidadeRegulatoriaESancoes")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.emAtendimentoAsNormasNacionaisEInternacionaisDe")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.limitacaoDoValorIndenizavel")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.naHipoteseDeResponsabilizacaoDaMundpayEstaFicara")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.reconhecimentoDoUsuario")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioReconheceQueAsDisposicoesDeIsencao")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.dosCanaisEHorariosDeAtendimento")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.emCasoDeDuvidasReclamacoesSugestoesOUsuario")}</p>
      <h2>{t("legal.pages.termsOfUse.blocks.dasDisposicoesFinais")}</h2>
      <p>{t("legal.pages.termsOfUse.blocks.eVedadoAoUsuarioCederTransferirOuDe")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.doDireitoDeRegressoEDasIndenizacoesA")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.aoAceitarEstesTermosDeUsoOUsuario2")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aObrigacaoDeIndenizarIncluiSemLimitacaoDespesas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oUsuarioObrigaSeAindaAManterIndenes")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aEventualToleranciaDeQualquerDasPartesQuanto")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.naHipoteseDeNecessidadeDeAdocaoDeMedidas")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.daSolucaoConsensualDeConflitos")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.asPartesComprometemSeAEnvidarSeusMelhores")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.doForo")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.asPartesElegemOForoDaComarcaDo")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.daLeiAplicavel")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.estesTermosDeUsoEARelacaoJuridica")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.resolucaoDeControversias")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.asControversiasDecorrentesOuRelacionadasAEstesTermos")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aArbitragemConstituiraOForoExclusivoDeResolucao")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aConducaoDoProcedimentoArbitralObservaraAsRegras")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.salvoAjusteDiversoEntreAsPartesAsAudiencias")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.osCustosTaxasAdministrativasEHonorariosArbitraisObservarao")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oArbitroPoderaConcederMedidasDeclaratoriasOuInjuntivas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.ficaEstabelecidaARenunciaExpressaAParticipacaoEm")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.paraFinsDeDireitoMaterialAplicavelEsteContrato")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.aEleicaoDaViaArbitralNaoImpedeComo")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.oAjuizamentoDeDemandasPeranteJuizadosDePequenas")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.aBuscaDeMedidasCautelaresOuTutelasDe")}</p>
      <h3>{t("legal.pages.termsOfUse.blocks.direitoDeRecusaDaArbitragemOptOutArbitration")}</h3>
      <p>{t("legal.pages.termsOfUse.blocks.naoObstanteAObrigatoriedadeDaArbitragemPrevistaNesta")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.paraOExercicioValidoDoOptOutO")}</p>
      <h4>{t("legal.pages.termsOfUse.blocks.aNotificacaoDeveraConterNoMinimo")}</h4>
      <p>{t("legal.pages.termsOfUse.blocks.nomeCompletoOuRazaoSocial")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.enderecoCadastrado")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.eMailVinculadoAConta")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.identificadorDaContaOuMerchantId")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.declaracaoExpressaDeRecusaAClausulaDeArbitragem")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oEnvioDeveraSerRealizadoParaOCanal")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oNaoExercicioDoDireitoDeOptOut")}</p>
      <p>{t("legal.pages.termsOfUse.blocks.oExercicioDoOptOutNaoAfetaraO")}</p>
    </>
  );
}

export function TermsOfUsePage() {
  const { i18n } = useTranslation();
  const isPortuguese = i18n.resolvedLanguage?.toLowerCase().startsWith("pt");

  return (
    <LegalLayout>
      <LegalDocument>
        {isPortuguese ? <PortugueseLegalContent /> : <EnglishLegalContent />}
      </LegalDocument>
    </LegalLayout>
  );
}
